version: "3"
services:
  web:
    build:
      context: ./ui/web
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    depends_on:
      - api-inv
    environment:
      - REACT_APP_API_HOST=172.18.0.3
      - API_PORT=5000
  api-inv:
    build:
      context: ./api/inventory
      dockerfile: Dockerfile.api
    ports:
      - "5000"
    depends_on:
      - mongo-db
    environment:
      - DATABASE_HOST=mongo-db-svr
      - DATABASE_USER=
      - DATABASE_PASSWORD=
      - DATABASE_NAME=items
      - DATABASE_PORT=27017
    networks:
      default:
        aliases:
          - api-inv-svr
  mongo-db:
    image: mongo
    volumes:
      - "./data/mongo:/data/db"
    ports:
      - "27017"
    networks:
      default:
        aliases:
          - mongo-db-svr
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=orderdb
      - MYSQL_ROOT_PASSWORD=sqlpassword
    ports:
      - "3306:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql"
      - "./tools/mysql:/docker-entrypoint-initdb.d"
