version: "3"
services:
  web:
    build:
      context: ./ui/web
      dockerfile: Dockerfile.web
    ports:
      - "3000:3000"
    depends_on:
      - api-inv
    environment:
      - REACT_APP_API_HOST=0.0.0.0
      - API_PORT=5000
  api-inv:
    build:
      context: ./api/inventory
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - DATABASE_HOST=mongo
      - DATABASE_USER=
      - DATABASE_PASSWORD=
      - DATABASE_NAME=items
      - DATABASE_PORT=27017
  mongo:
    image: mongo
    volumes:
      - "./data/mongo:/data/db"
    ports:
      - "27017:27017"
